version: '3.8'
services:
  persistence_api:
    image: jacobouribe/persistence_api
    container_name: persistence_api
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000